config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  
  #devise_for :pto_users
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  resources :project_causes

  resources :users do
  	resources :user_votes
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pto_users
  has_many :users
  has_many :pto_tasks
  has_many :project_causes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
  class Authentication < ApplicationRecord
     belongs_to :user

     def self.create_with_omniauth(auth_hash)
       self.new(
         provider: auth_hash["provider"],
         uid: auth_hash["uid"],
         token: auth_hash["credentials"]["token"]
       )
     end

     def update_token(auth_hash)
       self.token = auth_hash["credentials"]["token"]
       self.save
     end
  end
end

app/models/project_cause.rb
class ProjectCause < ApplicationRecord
	belongs_to :admin_users
	has_many :pto_tasks
end

app/models/pto_task.rb
class PtoTask < ApplicationRecord
	belongs_to :project_causes
	has_many :pto_users
	has_many :admin_users
end

app/models/pto_user.rb
class PtoUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_acceptance_of :pto_user_role
  validates_acceptance_of :admin_user_role
end

app/models/user_vote.rb
class UserVote < ApplicationRecord
	belongs_to :user
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def index
		@listings = ProjectCause.where(project_status: 0)
	end

	def new	
	end

	def show
		# byebug
		@listing = ProjectCause.find(params[:id])
	end

	private

	def listing_params
	 	params.require(:projectcause).permit(:project_title, :project_discription, :donation_goal, :project_status)
	end
end

app/controllers/pto_tasks_controller.rb
class PtoTasksController < ApplicationController
	before_action :authenticate_user!, :except [:new]
	
	def new
		@pto_task = PtoTask.new
	end

	def edit
	end

	def show
		@pto_task = PtoTask.find(params[:id])
	end

	def update
		@pto_task = current_user.pto_task.new(pto_task_params)

		respond_to do |format|
      	if @pto_task.update(pto_task_params)
        	format.html { redirect_to @pto_task, notice: 'Task @pto_task.id was added!' }
        	format.json { render action: "show", status: :created, location: @pto_task }
      	else
        	format.html { render action: "edit" }
        	format.json { render json: @pto_task.errors, status: :unprocessable_entity }
      	end
	end

	def create
		@pto_task = current_user.pto_task.new(pto_task_params)
		@pto_task.save
	end

	private
		def pto_task_params
			params.require(:pto_tasks).permit(:project_id, :task_title, :task_description, 
				:task_owner_approval_status,:task_admin_approval_status,
				:task_owner_id,:admin_owner_id)
		end

end

app/controllers/pto_users_controller.rb
class PtoUserController < ApplicationController
end

app/controllers/sessions_controller.rb
	class SessionsController < Clearance::SessionsController
    def create_from_omniauth
      auth_hash = request.env["omniauth.auth"]
      authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

      # if: previously already logged in with OAuth
      if authentication.user
        user = authentication.user
        authentication.update_token(auth_hash)
        @next = root_url
        @notice = "Signed in!"
      # else: user logs in with OAuth for the first time
      else
        user = User.create_with_auth_and_hash(authentication, auth_hash)
        # you are expected to have a path that leads to a page for editing user details
        @next = edit_user_path(user)
        @notice = "User created. Please confirm or edit details"
      end

      sign_in(user)
      redirect_to @next, :notice => @notice
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user , except: [:index, :show]

  def index
  end
  
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was added!"}
        format.json { render action: "show", status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @users.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User info was updated" }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/admin_user_helper.rb
module AdminUserHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demographic_helper.rb
module DemographicHelper
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/helpers/project_cause_helper.rb
module ProjectCauseHelper
end

app/helpers/pto_task_helper.rb
module PtoTaskHelper
end

app/helpers/pto_user_helper.rb
module PtoUserHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_votes_helper.rb
module UserVotesHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/index.html.erb
<h1>Welcome to Ripply </h1>

<% if !current_user.nil? %>
		<%= link_to "Causes", project_causes_path %><br>
		<%= link_to "My Causes" %><br>
		<%= link_to "Volunteer" %><br>
		<%= link_to "Karma Points" %><br>
	<hr>
	<p> Have a social pain, that you want solved? </p>
		<%= link_to "Become a Project Task Owner" %> 
	<p> Lets work together to try resolve it </p>
	<%# session.inspect %>
<% end %>

app/views/users/new.html.erb
<%#= provide(:title, "Signup") %>

<h1>Sign Up Now!</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for @user do |f| %>
		<%#= render 'shared/error_messages' %>
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control'  %>
		<%= f.label :email %>
		<%= f.text_field :email, class: 'form-control'  %>
		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control'  %>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, class: 'form-control'  %>
		<%#= f.label :profile_photo %>
		<%#= f.file_field :profile_photo %>
		<%= f.submit "Click here to create your account!", class: "btn btn-primary" %>
	<% end %>
  </div>
</div>

app/views/users/show.html.erb
<%#= provide(:title, "#{@user.name}'s Profile")%>

<div class="user-profile">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%#= avatar_for @user %>
          <%= @user.name %>
        </h1>
        <%= @user.email %>
      </section>
    </aside>
  </div>
<p>TEST</p>